# Generated by Django 4.2.21 on 2025-05-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('photo_url', models.CharField(max_length=80)),
            ],
        ),
    ]
